//
// Generated file, do not edit! Created by opp_msgtool 6.1 from SRC/CSNMP.msg.
//

#ifndef __CSNMP_M_H
#define __CSNMP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SNMPRequest;
class SNMPResponse;
/**
 * Class generated from <tt>SRC/CSNMP.msg:1</tt> by opp_msgtool.
 * <pre>
 * message SNMPRequest
 * {
 *     int requestId;
 *     string oid;      // object identifier
 *     int type;        // 0 = get, 1 = set
 *     string value;    // used for SET
 * }
 * </pre>
 */
class SNMPRequest : public ::omnetpp::cMessage
{
  protected:
    int requestId = 0;
    omnetpp::opp_string oid;
    int type = 0;
    omnetpp::opp_string value;

  private:
    void copy(const SNMPRequest& other);

  protected:
    bool operator==(const SNMPRequest&) = delete;

  public:
    SNMPRequest(const char *name=nullptr, short kind=0);
    SNMPRequest(const SNMPRequest& other);
    virtual ~SNMPRequest();
    SNMPRequest& operator=(const SNMPRequest& other);
    virtual SNMPRequest *dup() const override {return new SNMPRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual const char * getOid() const;
    virtual void setOid(const char * oid);

    virtual int getType() const;
    virtual void setType(int type);

    virtual const char * getValue() const;
    virtual void setValue(const char * value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SNMPRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SNMPRequest& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>SRC/CSNMP.msg:8</tt> by opp_msgtool.
 * <pre>
 * message SNMPResponse
 * {
 *     int requestId;
 *     string oid;
 *     string value;    // returned value
 *     int errorStatus; // 0 = ok, 1 = noSuchName, etc.
 * }
 * </pre>
 */
class SNMPResponse : public ::omnetpp::cMessage
{
  protected:
    int requestId = 0;
    omnetpp::opp_string oid;
    omnetpp::opp_string value;
    int errorStatus = 0;

  private:
    void copy(const SNMPResponse& other);

  protected:
    bool operator==(const SNMPResponse&) = delete;

  public:
    SNMPResponse(const char *name=nullptr, short kind=0);
    SNMPResponse(const SNMPResponse& other);
    virtual ~SNMPResponse();
    SNMPResponse& operator=(const SNMPResponse& other);
    virtual SNMPResponse *dup() const override {return new SNMPResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual const char * getOid() const;
    virtual void setOid(const char * oid);

    virtual const char * getValue() const;
    virtual void setValue(const char * value);

    virtual int getErrorStatus() const;
    virtual void setErrorStatus(int errorStatus);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SNMPResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SNMPResponse& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SNMPRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<SNMPRequest*>(ptr.get<cObject>()); }
template<> inline SNMPResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<SNMPResponse*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CSNMP_M_H

